title: Wayward Biochemist
author: Shane Gordon
# email: shagord.public@gmail.com
description: Musings on science & programming.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://waywardbiochemist.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WaywardBiochem
github_username:  s-gordon

# SEO PLUGIN
social:
  name: Shane Gordon
  links:
    - https://twitter.com/WaywardBiochem
    - https://github.com/s-gordon
    # - https://www.linkedin.com/in/BenBalter
    # - https://plus.google.com/+BenBalter
    # - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Archive', link: '/categories'}

tagline: >
  Musings on science & programming.

hero_img: posts/sleek_lg.jpeg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: waywardbiochemist@gmail.com # email for form submission

twitter_username: WaywardBiochem # replace with your_twitter_username or comment to remove link from footer
github_username:  s-gordon # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: waywardbiochemist # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
